# Generated by Django 6.0.7 on 2026-07-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="last_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
