# Generated by Django 6.0.7 on 2026-08-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="otp",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
