# Generated by Django 6.0.7 on 2026-07-31 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_token_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Username must be 3-30 characters and contain only letters, numbers, and underscores.",
                        regex="^[a-zA-Z0-9_]{3,30}$",
                    )
                ],
            ),
        ),
    ]
